### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by henry2778** [anedovba/homeworks#2]
Плиз, добавьте папочки с домашкам, чтоб было понятно с какой пары какие. Лучше всего пронумеровать )

**Comment by anedovba** [comment]
задания в файликах индекс + название папки в которой решения. (index_arrays_loops_tasks.php). все выполненные задания разбиты на папки (arrays_loops_tasks, php_basics_tasks). функции выложу позже. Как то по другому организовать ?
